### ISSUE TITLE
it seems does't work.

### ISSUE THREAD

**Issue by welaing** [hangxingliu/chrome-avgle-helper#1]
would you please tell me how to use it ?

**Comment by hangxingliu** [comment]
> Navigate to chrome://extensions in chrome.
> Check Developer mode on, then click Load Unpacked Extension.
> Choose this project folder.
> (Optional) You can delete this folder. (Because All extension codes have been copied into Chrome by Chrome)

> 在Chrome地址框中输入 chrome://extensions 回车
> 选中 开发者模式 然后点击 加载已解压的扩展程序…
> 选择 这个项目的目录
> (可选的) 你现在可以删除这个文件夹了 (因为 Chrome 已经把插件的代码都加载到 Chrome 的文件夹下了)

**Comment by hangxingliu** [comment]
Actually, the script `Avgle` is used for Linux/MacOS system. If you are Windows user. you should enable linux-subsytem function on Windows to use it.

`Avgle`的这个脚本文件是给Linux/MacOS的用户使用的. 如果你是Windows用户. 你可以开启linux-subsystem 功能,在Windows的子bash系统下使用

**Comment by welaing** [comment]
I am grateful for your help.I forgot to tell you that i am a Windows user,and i will try it on my another pc.
