### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by yobailover** [hangxingliu/chrome-avgle-helper#3]
Avgle has added some kind of check.
403 forbidden will show up during wget the m3u8 or ts file.

**Comment by hangxingliu** [comment]
Added `Referer` request header. And fixed

**Comment by yobailover** [comment]
Good news, or,,, bad news.
ahcdn has remove referer check.
With better_wget cannot download, it seems that you need to rollback AvgleDownloader.
Without better_wget download okay
