### ISSUE TITLE
Can support multi-threading?

### ISSUE THREAD

**Issue by dekura** [hangxingliu/chrome-avgle-helper#5]
I successfully installed and downloaded the video, but it is very slow, and it should increase speed if multi-threaded download is supported.
Anyway, thanks 😄

**Comment by hangxingliu** [comment]
Maybe I will add **axel**(<https://github.com/axel-download-accelerator/axel>) into downloader script for multi-threading.

**Comment by hangxingliu** [comment]
@dekura I make it support multi-thread now. (multi-thread support from **aria2** <https://github.com/aria2/aria2>)

I think it is very quick now, lol

**Comment by dekura** [comment]
You are awesome! 👍

**Comment by yobailover** [comment]
You are awesome! 
aria2c is a good tool. It is very useful to use aria2c download from openload and many other source too.
