### ISSUE TITLE
Windows user

### ISSUE THREAD

**Issue by MakiMyAngeru** [hangxingliu/chrome-avgle-helper#6]
I'm a windows user and I'm not sure where to put the bash scripts. 
Using the extension, the online player page gives me the download command but I don't know how to execute it.
Using command prompt gives me an error:
`'AvgleDownloader' is not recognized as an internal or external command, operable program or batch file.`
How do I execute the download command?

**Comment by hangxingliu** [comment]
Actually. The download script and merge script are designed for Linux and OS X systems. But if you want to use scripts on Windows. You can also use it in `Windows Subsystem for Linux` (At least Windows 10).

Guide documents: <https://docs.microsoft.com/en-us/windows/wsl/install-win10>

And after you install it, you can use shortcut `Win + R` to open `Run` dialog. And then input `bash` in the input box and press `Enter` to enter bash enviornment.

And the install dependencies, for example: `sudo apt install ffmpeg wget gawk -y` (command for Ubuntu)
Then `git clone https://github.com/hangxingliu/chrome-avgle-helper.git`
And you can use scripts now.

**Comment by hangxingliu** [comment]
After clone latest repository. You can use scripts simple in `Git Bash` after install dependencies.

**Comment by hangxingliu** [comment]
Actually, You can create a directory named `bin` in your user home directory (The path looks like: `C:\Users\Administrator\bin`)

And copy two scripts and `windows-libs` into the new directory. Then you can use script `Avgle`and `AvgleDownloader` in `Git Bash`.

---

And I will complete Windows section in README and replace combine by parent directory name to a better way in script `Avgle` later.
