### ISSUE TITLE
Injection doesn't work on particular videos/CDNs

### ISSUE THREAD

**Issue by bdingdong** [hangxingliu/chrome-avgle-helper#7]
There seems to be an issue on videos that are associated with cdn.qooqlevideo.com, while videos that go to ahcdn.com are fine. For example, this 

https://avgle.com/video/kQoYrYEd1Yk/%E5%A4%A7%E4%B9%B1%E4%BA%A4%E8%A7%A3%E7%A6%81-%E3%83%81-%E3%83%9D21%E6%9C%ACvs%E8%BE%BB%E6%9C%AC%E6%9D%8F-%E5%B8%B8%E3%81%AB%E8%82%89%E6%A3%92%E3%82%92%E6%B1%82%E3%82%81%E3%81%A6%E3%82%A4%E3%82%AB%E3%82%BB%E5%90%88%E3%81%86%E3%83%8E%E3%83%B3%E3%82%B9%E3%83%88%E3%83%83%E3%83%97%E5%A4%A7%E9%87%8F%E5%B0%84%E7%B2%BE26%E9%80%A3%E7%99%BA-%E8%B6%85%E4%B9%B1%E4%BA%A4%E3%82%B9%E3%83%9A%E3%82%B7%E3%83%A3%E3%83%AB-ssni-120

works because request goes to ahcdn.com (filtering the .m3u8 file using chrome://net-internals), but videos like this:

https://avgle.com/video/1MkMJM1fmM2/%E9%AB%98%E6%B8%85%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95-pred-110-%E7%B5%B6%E5%AF%BE%E9%A0%98%E5%9F%9F%E3%83%8B%E3%83%BC%E3%83%8F%E3%82%A4%E3%81%8A%E5%A7%89%E3%81%95%E3%82%93%E3%81%AB%E8%81%96%E6%B0%B4%E3%81%8B%E3%81%91%E3%82%89%E3%82%8C%E7%97%B4%E5%A5%B3%E3%82%89%E3%82%8C%E3%82%8B-%E9%BA%BB%E5%80%89%E6%86%82-%E7%B5%95%E5%B0%8D%E9%A0%98%E5%9F%9F%E5%B0%84%E6%BB%BF%E8%81%96%E6%B0%B4%E9%BA%BB%E5%80%89%E5%84%AA

and

https://avgle.com/video/WBBaJaEYmaH/%E9%AB%98%E6%B8%85%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95-pred-111-%E5%B1%88%E8%BE%B1%E3%81%AE%E4%BF%9D%E8%AD%B7%E8%80%85%E4%BC%9A-%E6%BF%83%E5%8E%9A%E8%A6%AA%E7%88%B6%E3%81%AE%E6%B1%97-%E6%B6%8E-%E7%B2%BE%E6%B6%B2%E3%81%BE%E3%81%BF%E3%82%8C%E5%AD%95%E3%81%BE%E3%81%9B%E8%BC%AA%E5%A7%A6-%E5%B1%B1%E5%B2%B8%E9%80%A2%E8%8A%B1-%E5%B1%88%E8%BE%B1%E5%AE%B6%E9%95%B7%E6%9C%83%E8%A2%AB%E5%85%B6%E4%BB%96%E7%94%B7%E4%BA%BA%E7%B2%BE%E6%B6%B2%E7%8E%B7%E6%B1%A1

do not work. Furthermore, I think videos with cdn.qooqle.com has the 403 error that you fixed previously because I suspect that this CDN does a check on the referrer.

**Comment by hangxingliu** [comment]
@bdingdong  I update it at latest commit. I verified it is work on my computer. And you can have a try later. You can close this issue if the latest version could be work with you.
