### ISSUE TITLE
support https://www.av01.tv/

### ISSUE THREAD

**Issue by happystefan** [hangxingliu/chrome-avgle-helper#8]
Hi,

https://www.av01.tv/ is a good sites which have lots of high quality videos. Is it difficult to add support  for https://www.av01.tv/?

**Comment by hangxingliu** [comment]
No plans yet. But you modify this project by yourself if the website you mentioned use the same way to load video (`xxx.m3u8`)

**Comment by hangxingliu** [comment]
@happystefan You can watch this repo. And I will add more websites example into it in the future.

**Comment by yobailover** [comment]
@happystefan 
for the website you mentioned, you can use following chrome extension to catch m3u8 file.
use wget or aria2c to download each files listed in the m3u8 file.
Then use ffmpeg to concat them.

https://chrome.google.com/webstore/detail/flash-video-downloader/aiimdkdngfcipjohbjenkahhlhccpdbc

**Comment by yobailover** [comment]
@happystefan there's no need to develop a extension for the website you mentioned.
Since it is too easy to catch m3u8 file.

On the contrary, Avgle is another case, it hides the m3u8 file so well.
You have to use an extension to catch it.

**Comment by happystefan** [comment]
@yobailover Great thanks! Will have a try!

**Comment by hangxingliu** [comment]
@happystefan Yes, you can just following the way yobailover introduced. I explored many online video sites, most of their videos can be accessed by using m3u8 link or set `content-range` header. So you can use `wget` or `aira2` to download most video in online video site.

And use `ffmpeg` to merge them. Example: <https://github.com/hangxingliu/chrome-avgle-helper/blob/master/Avgle#L173>
